from typing import Protocol, runtime_checkable


@runtime_checkable
class CoverProtocol(Protocol):
    async def open(self) -> None: ...
    async def close(self) -> None: ...
    async def stop(self) -> None: ...
    async def set_current_position(self, position: int) -> None: ...

    @property
    def current_position(self) -> int | None: ...

    @property
    def is_closed(self) -> bool: ...

    @property
    def is_closing(self) -> bool: ...

    @property
    def is_opening(self) -> bool: ...

    def supports_open(self) -> bool: ...
    def supports_close(self) -> bool: ...
    def supports_stop(self) -> bool: ...
    def supports_position(self) -> bool: ...
